---
title: "Paper Introduction Rough Draft 6/22"
author: "Henry Shiffer"
date: "22/06/2021"
output: github_document
---

The COVID-19 pandemic and resulting stay-at-home orders and social distancing measures increased the importance of housing and personal space, while simultaneously changing the social fabric of society. While all employment and economic sectors were forced into some change, the small business economy and the tourism industry saw very dramatic changes happening quickly. Since the start of the COVID-19 outbreak, 70% of Canadian small businesses had seen a drop in revenues by 30% or more, and it is anticipated there will be a slower recovery for small businesses once the pandemic is over (Mo et al., 2020). For tourism, the restrictions on travel in Canada have led international arrivals in Canada to fall 54.2% in March 2020 when compared to February 2020 (Liu, 2020), and hotel occupancy rates were below 20% by the beginning of April 2020 (Liu, 2020).
  

With the fluctuating COVID-19 restrictions on travel, and with the risks that travelling during COVID-19 impose, it is no question that Airbnb whose market relies heavily on tourism has taken a significant hit during the COVID-19 pandemic. Local Lockdowns resulted in a 57.8% fall in global Airbnb booking activities (Hu & Lee, 2020). According to CNBC in May 2020, Airbnb had laid off a quarter of its workforce (Bosa & Rodriguez, 2020) and with no end to the pandemic in sight, there is no way to predict if the organization will ever recover it’s pre-pandemic success. This loss, while significant to the Airbnb organization, can be felt much further down by Airbnb hosts. Many hosts, whose primary income comes from rental of the units they provide, are stuck with bills and mortgages to pay, sometimes for many units.
  
In March 2020, Ontario Premier Doug Ford declared a provincial state of emergency which prompted the closing of many non-essential businesses and facilities across Ontario. In late July 2020, Toronto and Peel region were allowed to enter stage 3 of the Ontario reopening plan. In October 2020, Peel region, Toronto and Ottawa were rolled back to modified stage 2 for 28 days. In November 2020, Doug Ford announced that the province would move towards a 5-tier system to determine restrictions. Mid-November Toronto was announced to move into the Red Tier “Control” to provide more restrictions, and finally on November 20th, Ford announced Toronto and Peel region would be moved into Lockdown effective November 23rd. This prompted all non-essential businesses to be closed along with all dine-in restaurants, gyms, and personal care services. In January 2021, Doug Ford declared a second declaration of emergency, and stay-at-home orders were declared for the province. In March 2021, Toronto and Peel region were able to exit stay-at-home orders and Toronto and Peel region entered Grey Tier “Lockdown”. In April 2021, Ford announced the province would move into White Tier “Shutdown”, which would impose the same measures put in place during the original province wide shutdown in March 2020.

Ontario and the city of Toronto have placed an increased control on the Airbnb and short-term rental market during the COVID-19 outbreak. In April 2020, Ontario had banned all short term rentals (a rental period of less than 28 days) unless the unit is being rented to someone in need of housing during the “Emergency Order” (Eisenberg & Shrives, 2020). In September 2020, Toronto laid out a series of short term rental reforms. These reforms require short-term rental operators to need to register with the city in order to allow short-term tenants (Stevens, 2020). The reforms also state that these landlords may only be allowed to rent out their primary residence for up to 180 nights per year.
	

Using Toronto Airbnb data from February 2020 to April 2021, this paper will explore how price has varied with relation to an Airbnb listing’s quality over the course of the pandemic. This paper will primarily focus on Airbnb listings around the University of Toronto. These neighbourhoods being: Kensington-Chinatown, Annex, University, Church-Yonge Corridor, and Bay Street Corridor. This paper defines a criteria to measure an Airbnb listing’s quality, and models to represent this criteria. 





**Sources to properly cite in paper:**


Mo et al article:
(https://utpjournals.press/doi/pdf/10.3138/cpp.2020-072)

Liu article:
https://www150.statcan.gc.ca/n1/en/pub/11-626-x/11-626-x2020023-eng.pdf?st=heZbrsKV


Life satisfaction article:
https://www150.statcan.gc.ca/n1/en/pub/11f0019m/11f0019m2020020-eng.pdf?st=fb_GyrDY

Airbnb CNBC layoff article:
https://www.cnbc.com/2020/05/05/airbnb-to-lay-off-nearly-1900-people-25percent-of-company.html


Global Airbnb Article:
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3589141

Toronto short term rentals:
https://www.weirfoulds.com/the-long-term-impact-of-covid-19-on-short-term-rentals

Housing reform September:
https://shorttermrentalz.com/news/toronto-rental-reforms-september/




